server:
  port: 8762

eureka:
  instance:
    hostname: host2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/, http://127.0.0.1:8763/eureka/


#spring.cloud.config.discovery.enabled: true

spring:
  application:
    name: eureka2
