server:
  port: 8761

eureka:
  instance:
    hostname: host1
  client:
    register-with-eureka: true
    fetch-registry: truee
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/


spring.cloud.config.discovery.enabled: true

spring:
  application:
    name: eureka1
