server:
  port: 8763

eureka:
  instance:
    hostname: host3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/


spring.cloud.config.discovery.enabled: true

spring:
  application:
    name: eureka3
