server:
  port: 9987

spring:
  datasource:
    schema: classpath:/mysql_init.sql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myzipkin?characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678
    initialization-mode: always
    max-active: 20
    min-idle: 5
    max-wait: 60000
    time-between-eviction-runs-millis: 300000
    validation-query: select 1 from dual
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-pre-connection-size: 20

    filters: stat,wall,log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  sleuth:
    enable: false

  zipkin:
    storage:
      type: mysql

  eureka:
    client:
      serviceUrl:
        defaultZone: http:localhost:8761/eureka/

  ribbon.ConnectTimeout: 5000
  ribbon.ReadTimeout: 10000


