

  sleuth:
    sampler:
#      日志采样百分比 默认 0。1
      probability: 0.1

server:
  port: 9102
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug
